### PR TITLE
A couple of compilation fixes on the latest Ubuntu.

### PR DESCRIPTION
**Pull request by Tvangeste**

### CODE REVIEW

**Comment by CrazyCoder** [comment]
I build on Ubuntu 12.10 with gcc 4.7.2 and have no compilation issues. Building from Qt Creator 2.6 with Qt 4.7.4 works fine.

**Comment by Tvangeste** [comment]
To be precise, I'm on Lubuntu 12.10. Can you show me the compilation error for further investigation? :)

The changes seem simple enough and I'm quite surprised they could lead to any compilation errors at all.

P.S. I use Qt Creator 2.5.2 and Qt 4.8.3 though...

**Comment by CrazyCoder** [comment]
I have no compilation errors WITHOUT your changes, I have unrelated linker error WITHOUT your changes. I didn't try these changes yet as I don't think they are required.

**Comment by CrazyCoder** [comment]
Thanks for the patch, it fixed the problem with compilation that I didn't notice because linking was failing because of incorrect libraries order.
